server:
  port: 8082

  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:cert/server.jks
    key-store-password: nt-service
    key-alias: nt-ms
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:cert/server.jks
    trust-store-password: nt-service
    trust-store-type: JKS


keycloak:
  realm: cmopg
  auth-server-url: http://localhost:9090/auth
  ssl-required: external
  resource: cmo_backend
  bearer-only: true
  use-resource-role-mappings: true


logging:
  level:
    root: debug
