server:
  port: 8082

  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:cert/server.p12
    key-store-password: 12345678
    key-alias: digipay
    key-store-type: PKCS12
    key-store-provider: SUN
    trust-store: classpath:cert/server.p12
    trust-store-password: 12345678
    trust-store-type: PKCS12


keycloak:
  realm: cmopg
  auth-server-url: http://localhost:9090/auth
  ssl-required: external
  resource: cmo_backend
  bearer-only: true
  use-resource-role-mappings: true


logging:
  level:
    root: debug
